// test data for dev display

import { Team } from '../class/team';
import { Event } from '../class/event';
import { Game } from '../class/game';

export const GAMES: Game[] = [
    {
        'id': 1,
        'month': 9,
        'day': 2,
        'time': '9 AM',
        'name': 'Game 1',
        'team1Id': 2,
        'team2Id': 9,
        'location': 'yeag',
        'referee': 'Desire Dotson',
        'played': true,
        'team1goals': 8,
        'team2goals': 2
    },
    {
        'id': 2,
        'month': 9,
        'day': 2,
        'time': '1 PM',
        'name': 'Game 2',
        'team1Id': 3,
        'team2Id': 8,
        'location': 'hart',
        'referee': 'Nicholle Nickelson',
        'played': true,
        'team1goals': 2,
        'team2goals': 0
    },
    {
        'id': 3,
        'month': 9,
        'day': 9,
        'time': '9 AM',
        'name': 'Game 3',
        'team1Id': 4,
        'team2Id': 7,
        'location': 'north',
        'referee': 'Kirstie Killoran',
        'played': true,
        'team1goals': 0,
        'team2goals': 2
    },
    {
        'id': 4,
        'month': 9,
        'day': 9,
        'time': '1 PM',
        'name': 'Game 4',
        'team1Id': 5,
        'team2Id': 6,
        'location': 'south',
        'referee': 'Estrella Eldreth',
        'played': true,
        'team1goals': 0,
        'team2goals': 1
    },
    {
        'id': 5,
        'month': 9,
        'day': 16,
        'time': '9 AM',
        'name': 'Game 5',
        'team1Id': 1,
        'team2Id': 9,
        'location': 'green',
        'referee': 'Ena Erben',
        'played': true,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 6,
        'month': 9,
        'day': 16,
        'time': '1 PM',
        'name': 'Game 6',
        'team1Id': 2,
        'team2Id': 7,
        'location': 'yeag',
        'referee': 'Desire Dotson',
        'played': true,
        'team1goals': 1,
        'team2goals': 4
    },
    {
        'id': 7,
        'month': 9,
        'day': 23,
        'time': '9 AM',
        'name': 'Game 7',
        'team1Id': 3,
        'team2Id': 6,
        'location': 'hart',
        'referee': 'Nicholle Nickelson',
        'played': true,
        'team1goals': 7,
        'team2goals': 9
    },
    {
        'id': 8,
        'month': 9,
        'day': 23,
        'time': '1 PM',
        'name': 'Game 8',
        'team1Id': 4,
        'team2Id': 5,
        'location': 'north',
        'referee': 'Francene Finnen',
        'played': true,
        'team1goals': 0,
        'team2goals': 1
    },
    {
        'id': 9,
        'month': 9,
        'day': 30,
        'time': '9 AM',
        'name': 'Game 9',
        'team1Id': 1,
        'team2Id': 8,
        'location': 'green',
        'referee': 'Sergio Shimp',
        'played': true,
        'team1goals': 0,
        'team2goals': 2
    },
    {
        'id': 10,
        'month': 9,
        'day': 30,
        'time': '1 PM',
        'name': 'Game 10',
        'team1Id': 9,
        'team2Id': 7,
        'location': 'hart',
        'referee': 'Chung Cousineau',
        'played': true,
        'team1goals': 1,
        'team2goals': 0
    },
    {
        'id': 11,
        'month': 10,
        'day': 7,
        'time': '9 AM',
        'name': 'Game 11',
        'team1Id': 2,
        'team2Id': 5,
        'location': 'yeag',
        'referee': 'Earl Eveland',
        'played': true,
        'team1goals': 2,
        'team2goals': 1
    },
    {
        'id': 12,
        'month': 10,
        'day': 7,
        'time': '1 PM',
        'name': 'Game 12',
        'team1Id': 3,
        'team2Id': 4,
        'location': 'hart',
        'referee': 'Palmer Plasse',
        'played': true,
        'team1goals': 4,
        'team2goals': 2
    },
    {
        'id': 13,
        'month': 10,
        'day': 14,
        'time': '9 AM',
        'name': 'Game 13',
        'team1Id': 1,
        'team2Id': 7,
        'location': 'green',
        'referee': 'Kirstie Killoran',
        'played': true,
        'team1goals': 1,
        'team2goals': 3
    },
    {
        'id': 14,
        'month': 10,
        'day': 14,
        'time': '1 PM',
        'name': 'Game 14',
        'team1Id': 8,
        'team2Id': 6,
        'location': 'yeag',
        'referee': 'Sook Stiefel',
        'played': true,
        'team1goals': 2,
        'team2goals': 3
    },
    {
        'id': 15,
        'month': 10,
        'day': 21,
        'time': '9 AM',
        'name': 'Game 15',
        'team1Id': 9,
        'team2Id': 5,
        'location': 'hart',
        'referee': 'Desire Dotson',
        'played': true,
        'team1goals': 1,
        'team2goals': 2
    },
    {
        'id': 16,
        'month': 10,
        'day': 21,
        'time': '1 PM',
        'name': 'Game 16',
        'team1Id': 2,
        'team2Id': 3,
        'location': 'yeag',
        'referee': 'Sergio Shimp',
        'played': true,
        'team1goals': 7,
        'team2goals': 3
    },
    {
        'id': 17,
        'month': 10,
        'day': 28,
        'time': '9 AM',
        'name': 'Game 17',
        'team1Id': 1,
        'team2Id': 6,
        'location': 'green',
        'referee': 'Mozelle Mcgibbon',
        'played': true,
        'team1goals': 1,
        'team2goals': 0
    },
    {
        'id': 18,
        'month': 10,
        'day': 28,
        'time': '1 PM',
        'name': 'Game 18',
        'team1Id': 7,
        'team2Id': 5,
        'location': 'green',
        'referee': 'Estrella Eldreth',
        'played': true,
        'team1goals': 1,
        'team2goals': 0
    },
    {
        'id': 19,
        'month': 11,
        'day': 4,
        'time': '9 AM',
        'name': 'Game 19',
        'team1Id': 8,
        'team2Id': 4,
        'location': 'yeag',
        'referee': 'Chung Cousineau',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 20,
        'month': 11,
        'day': 4,
        'time': '1 PM',
        'name': 'Game 20',
        'team1Id': 9,
        'team2Id': 3,
        'location': 'hart',
        'referee': 'Nicholle Nickelson',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 21,
        'month': 11,
        'day': 11,
        'time': '9 AM',
        'name': 'Game 21',
        'team1Id': 1,
        'team2Id': 5,
        'location': 'green',
        'referee': 'Nicholle Nickelson',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 22,
        'month': 11,
        'day': 11,
        'time': '1 PM',
        'name': 'Game 22',
        'team1Id': 6,
        'team2Id': 4,
        'location': 'katz',
        'referee': 'Earnest Ebersole',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 23,
        'month': 11,
        'day': 18,
        'time': '9 AM',
        'name': 'Game 23',
        'team1Id': 7,
        'team2Id': 3,
        'location': 'green',
        'referee': 'Earl Eveland',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 24,
        'month': 11,
        'day': 18,
        'time': '1 PM',
        'name': 'Game 24',
        'team1Id': 8,
        'team2Id': 2,
        'location': 'yeag',
        'referee': 'Francene Finnen',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 25,
        'month': 11,
        'day': 25,
        'time': '9 AM',
        'name': 'Game 25',
        'team1Id': 1,
        'team2Id': 4,
        'location': 'green',
        'referee': 'Estrella Eldreth',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 26,
        'month': 11,
        'day': 25,
        'time': '1 PM',
        'name': 'Game 26',
        'team1Id': 5,
        'team2Id': 3,
        'location': 'south',
        'referee': 'Merle Marcellus',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 27,
        'month': 12,
        'day': 2,
        'time': '9 AM',
        'name': 'Game 27',
        'team1Id': 6,
        'team2Id': 2,
        'location': 'katz',
        'referee': 'Desire Dotson',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 28,
        'month': 12,
        'day': 2,
        'time': '1 PM',
        'name': 'Game 28',
        'team1Id': 8,
        'team2Id': 9,
        'location': 'yeag',
        'referee': 'Chung Cousineau',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 29,
        'month': 12,
        'day': 9,
        'time': '9 AM',
        'name': 'Game 29',
        'team1Id': 1,
        'team2Id': 3,
        'location': 'green',
        'referee': 'Francene Finnen',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 30,
        'month': 12,
        'day': 9,
        'time': '1 PM',
        'name': 'Game 30',
        'team1Id': 4,
        'team2Id': 2,
        'location': 'north',
        'referee': 'Earnest Ebersole',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 31,
        'month': 12,
        'day': 16,
        'time': '9 AM',
        'name': 'Game 31',
        'team1Id': 6,
        'team2Id': 9,
        'location': 'katz',
        'referee': 'Dani Diedrich',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 32,
        'month': 12,
        'day': 16,
        'time': '1 PM',
        'name': 'Game 32',
        'team1Id': 7,
        'team2Id': 8,
        'location': 'green',
        'referee': 'Deshawn Denton',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 33,
        'month': 12,
        'day': 23,
        'time': '9 AM',
        'name': 'Game 33',
        'team1Id': 1,
        'team2Id': 2,
        'location': 'green',
        'referee': 'Deshawn Denton',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 34,
        'month': 12,
        'day': 23,
        'time': '1 PM',
        'name': 'Game 34',
        'team1Id': 4,
        'team2Id': 9,
        'location': 'north',
        'referee': 'Nicholle Nickelson',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 35,
        'month': 12,
        'day': 30,
        'time': '9 AM',
        'name': 'Game 35',
        'team1Id': 5,
        'team2Id': 8,
        'location': 'south',
        'referee': 'Earnest Ebersole',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 36,
        'month': 12,
        'day': 30,
        'time': '1 PM',
        'name': 'Game 36',
        'team1Id': 6,
        'team2Id': 7,
        'location': 'katz',
        'referee': 'Chung Cousineau',
        'played': false,
        'team1goals': 0,
        'team2goals': 0
    },
    {
        'id': 37,
        'month': 1,
        'day': 6,
        'time': '9 AM',
        'name': 'Semifinal A',
        'team1Id': 0,
        'team2Id': 0,
        'location': 'north',
        'referee': 'Nicholle Nickelson',
        'played': false,
        'team1goals': 0,
        'team2goals': 0,
    },
    {
        'id': 38,
        'month': 1,
        'day': 6,
        'time': '1 PM',
        'name': 'Semifinal B',
        'team1Id': 0,
        'team2Id': 0,
        'location': 'south',
        'referee': 'Chung Cousineau',
        'played': false,
        'team1goals': 0,
        'team2goals': 0,
    },
    {
        'id': 39,
        'month': 1,
        'day': 13,
        'time': '9 AM',
        'name': 'Final',
        'team1Id': 0,
        'team2Id': 0,
        'location': 'katz',
        'referee': 'Estrella Eldreth',
        'played': false,
        'team1goals': 0,
        'team2goals': 0,
    }
];

export const EVENTS: Event[] = [
    {
        date: 'August 04',
        description: 'NYSL Fundraiser',
    },
    {
        date: 'August 16',
        description: 'Season Kick - off: Meet the Teams',
    },
    {
        date: 'September 1',
        description: 'First Game of the Season(Check Game Schedule for details)',
    },
];
export const TEAMS: Team[] = [
    {
        'id': 1,
        'name': 'U1',
        'home': 'green',
        'coach': 'Jacinto Johnstone',
        'rank': 6,
        'mp': 4,
        'win': 1,
        'loss': 2,
        'tie': 1,
        'goal_scored': 2,
        'goal_taken': 5
    },
    {
        'id': 2,
        'name': 'U2',
        'home': 'yeag',
        'coach': 'Gregg Grooms',
        'rank': 2,
        'mp': 9,
        'win': 3,
        'loss': 1,
        'tie': 0,
        'goal_scored': 18,
        'goal_taken': 10
    },
    {
        'id': 3,
        'name': 'U3',
        'home': 'hart',
        'coach': 'Kerstin Knarr',
        'rank': 1,
        'mp': 9,
        'win': 3,
        'loss': 1,
        'tie': 0,
        'goal_scored': 20,
        'goal_taken': 14
    },
    {
        'id': 4,
        'name': 'U4',
        'home': 'north',
        'coach': 'Jayson Jilek',
        'rank': 8,
        'mp': 3,
        'win': 1,
        'loss': 2,
        'tie': 0,
        'goal_scored': 4,
        'goal_taken': 5
    },
    {
        'id': 5,
        'name': 'U5',
        'home': 'south',
        'coach': 'Benito Barbara',
        'rank': 4,
        'mp': 6,
        'win': 2,
        'loss': 3,
        'tie': 0,
        'goal_scored': 4,
        'goal_taken': 5
    },
    {
        'id': 6,
        'name': 'U6',
        'home': 'katz',
        'coach': 'Inocencia Ito',
        'rank': 7,
        'mp': 3,
        'win': 1,
        'loss': 3,
        'tie': 0,
        'goal_scored': 10,
        'goal_taken': 13
    },
    {
        'id': 7,
        'name': 'U7',
        'home': 'green',
        'coach': 'Cleo Corsi',
        'rank': 5,
        'mp': 6,
        'win': 2,
        'loss': 3,
        'tie': 0,
        'goal_scored': 4,
        'goal_taken': 9
    },
    {
        'id': 8,
        'name': 'U8',
        'home': 'yeag',
        'coach': 'Noble Nester',
        'rank': 8,
        'mp': 3,
        'win': 1,
        'loss': 2,
        'tie': 0,
        'goal_scored': 4,
        'goal_taken': 5
    },
    {
        'id': 9,
        'name': 'U9',
        'home': 'hart',
        'coach': 'Margareta Muma',
        'rank': 3,
        'mp': 7,
        'win': 2,
        'loss': 1,
        'tie': 1,
        'goal_scored': 10,
        'goal_taken': 4
    },
    {
        'id': 0,
        'name': 'TBD',
        'home': '',
        'coach': '',
        'rank': 0,
        'mp': 0,
        'win': 0,
        'loss': 0,
        'tie': 0,
        'goal_scored': 0,
        'goal_taken': 0
    }
];
